// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : sim.v
// Top        : ProjectSoC
// Device     : LITEX_TOUR
// Hierarchy  : disabled
// LiteX sha1 : aa32cc0d4
// Date       : 2026-10-05 21:36:51
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module sim (
    input  wire          sim_trace,
    input  wire          sys_clk
);


//------------------------------------------------------------------------------
// Hierarchy
//------------------------------------------------------------------------------

/*
ProjectSoC
├── bus (SoCBusHandler)
│    ├── axilite2wishbone_0 (AXILite2Wishbone) [Gen]
│    │    └── fsm (FSM)
│    └── _interconnect (InterconnectShared)
│         ├── arbiter (Arbiter)
│         │    └── rr (RoundRobin)
│         ├── decoder (Decoder)
│         └── timeout (Timeout)
│              └── waittimer_0 (WaitTimer) [Gen]
├── csr (SoCCSRHandler)
├── irq (SoCIRQHandler)
├── cpu (VexiiRiscv)
│    ├── soc_bus (SoCBusHandler)
│    │    ├── axilite2wishbone_0 (AXILite2Wishbone) [Gen]
│    │    │    └── fsm (FSM)
│    │    └── _interconnect (InterconnectShared)
│    │         ├── arbiter (Arbiter)
│    │         │    └── rr (RoundRobin)
│    │         ├── decoder (Decoder)
│    │         └── timeout (Timeout)
│    │              └── waittimer_0 (WaitTimer) [Gen]
│    └── [BB:VexiiRiscvLitex_70fcb4655c102be1cd666acde65d5d70]
├── rom (SRAM)
├── write_target (WriteTarget)
├── crg (CRG)
├── csr_bridge (Wishbone2CSR)
│    └── fsm (FSM)
└── csr_bankarray (CSRBankArray)
Legend:
  [Gen]: Auto-generated instance name.
  [BB:NAME]: Blackbox instance (verilog Instance).

*/

//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------

reg           ack = 1'd0;
wire   [29:0] adr;
reg    [29:0] basiclowerer0 = 30'd0;
reg    [31:0] basiclowerer1 = 32'd0;
reg     [3:0] basiclowerer2 = 4'd0;
reg           basiclowerer3 = 1'd0;
reg           basiclowerer4 = 1'd0;
reg           basiclowerer5 = 1'd0;
reg     [2:0] basiclowerer6 = 3'd0;
reg     [1:0] basiclowerer7 = 2'd0;
reg    [31:0] basiclowerer_basiclowerer = 32'd0;
wire    [1:0] bte;
reg           crg = 1'd1;
wire    [2:0] cti;
wire          cyc;
reg    [31:0] dat_r = 32'd0;
wire   [31:0] dat_w;
reg     [2:0] decoder0 = 3'd0;
reg     [2:0] decoder1 = 3'd0;
wire          err;
reg     [2:0] fsm0 = 3'd0;
reg     [2:0] fsm1 = 3'd0;
reg           interface0_ack = 1'd0;
wire   [29:0] interface0_adr;
wire    [1:0] interface0_bte;
wire    [2:0] interface0_cti;
wire          interface0_cyc;
reg    [31:0] interface0_dat_r = 32'd0;
wire   [31:0] interface0_dat_w;
reg           interface0_err = 1'd0;
wire    [3:0] interface0_sel;
wire          interface0_stb;
wire          interface0_we;
reg    [13:0] interface1_adr = 14'd0;
reg    [31:0] interface1_dat_r = 32'd0;
reg    [31:0] interface1_dat_w = 32'd0;
reg           interface1_re = 1'd0;
reg           interface1_we = 1'd0;
wire          por_clk;
reg           projectsoc0 = 1'd0;
wire   [31:0] projectsoc1;
wire          projectsoc_adapted_interface_ack;
reg    [29:0] projectsoc_adapted_interface_adr = 30'd0;
reg     [1:0] projectsoc_adapted_interface_bte = 2'd0;
reg     [2:0] projectsoc_adapted_interface_cti = 3'd0;
reg           projectsoc_adapted_interface_cyc = 1'd0;
wire   [31:0] projectsoc_adapted_interface_dat_r;
reg    [31:0] projectsoc_adapted_interface_dat_w = 32'd0;
wire          projectsoc_adapted_interface_err;
reg     [3:0] projectsoc_adapted_interface_sel = 4'd0;
reg           projectsoc_adapted_interface_stb = 1'd0;
reg           projectsoc_adapted_interface_we = 1'd0;
reg    [31:0] projectsoc_axilite2wishbone0 = 32'd0;
reg    [31:0] projectsoc_axilite2wishbone0_lowernext0 = 32'd0;
reg           projectsoc_axilite2wishbone0_lowernext1 = 1'd0;
wire   [31:0] projectsoc_axilite2wishbone1;
wire   [31:0] projectsoc_axilite2wishbone2;
reg           projectsoc_axilite2wishbone3 = 1'd0;
reg           projectsoc_axilite2wishbone3_lowernext_lowernext0 = 1'd0;
reg           projectsoc_axilite2wishbone3_lowernext_lowernext1 = 1'd0;
reg           projectsoc_ram_bus_ack = 1'd0;
wire   [29:0] projectsoc_ram_bus_adr;
wire    [1:0] projectsoc_ram_bus_bte;
wire    [2:0] projectsoc_ram_bus_cti;
wire          projectsoc_ram_bus_cyc;
wire   [31:0] projectsoc_ram_bus_dat_r;
wire   [31:0] projectsoc_ram_bus_dat_w;
reg           projectsoc_ram_bus_err = 1'd0;
wire    [3:0] projectsoc_ram_bus_sel;
wire          projectsoc_ram_bus_stb;
wire          projectsoc_ram_bus_we;
reg           projectsoc_sram = 1'd0;
wire    [3:0] projectsoc_sram_memory0;
wire   [31:0] projectsoc_sram_memory1;
reg           projectsoc_vexiiriscv0 = 1'd0;
reg    [31:0] projectsoc_vexiiriscv1 = 32'd0;
wire    [7:0] projectsoc_vexiiriscv2;
wire          projectsoc_vexiiriscv3;
wire          projectsoc_vexiiriscv4;
wire   [31:0] projectsoc_vexiiriscv_endpoint0_payload_addr;
reg           projectsoc_vexiiriscv_endpoint0_ready = 1'd0;
wire          projectsoc_vexiiriscv_endpoint0_valid;
wire   [31:0] projectsoc_vexiiriscv_endpoint1_payload_data;
wire    [3:0] projectsoc_vexiiriscv_endpoint1_payload_strb;
reg           projectsoc_vexiiriscv_endpoint1_ready = 1'd0;
wire          projectsoc_vexiiriscv_endpoint1_valid;
reg     [1:0] projectsoc_vexiiriscv_endpoint2_payload_resp = 2'd0;
wire          projectsoc_vexiiriscv_endpoint2_ready;
reg           projectsoc_vexiiriscv_endpoint2_valid = 1'd0;
wire   [31:0] projectsoc_vexiiriscv_endpoint3_payload_addr;
reg           projectsoc_vexiiriscv_endpoint3_ready = 1'd0;
wire          projectsoc_vexiiriscv_endpoint3_valid;
reg    [31:0] projectsoc_vexiiriscv_endpoint4_payload_data = 32'd0;
reg     [1:0] projectsoc_vexiiriscv_endpoint4_payload_resp = 2'd0;
wire          projectsoc_vexiiriscv_endpoint4_ready;
reg           projectsoc_vexiiriscv_endpoint4_valid = 1'd0;
wire   [31:0] projectsoc_writetarget;
reg           projectsoc_writetarget_ack = 1'd0;
wire   [29:0] projectsoc_writetarget_adr;
wire    [1:0] projectsoc_writetarget_bte;
wire    [2:0] projectsoc_writetarget_cti;
wire          projectsoc_writetarget_cyc;
wire   [31:0] projectsoc_writetarget_dat_r;
wire   [31:0] projectsoc_writetarget_dat_w;
wire          projectsoc_writetarget_err;
wire    [3:0] projectsoc_writetarget_sel;
wire          projectsoc_writetarget_stb;
wire          projectsoc_writetarget_we;
wire          roundrobin0;
wire          roundrobin1;
wire    [3:0] sel;
wire          stb;
wire          sys_clk_1;
wire          sys_rst;
reg           timeout = 1'd0;
wire          timeout_waittimer0;
wire          timeout_waittimer1;
reg    [19:0] timeout_waittimer2 = 20'd1000000;
wire          we;
reg           wishbone2csr = 1'd0;
reg           wishbone2csr_fsm0 = 1'd0;
reg           wishbone2csr_fsm1 = 1'd0;

//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------

assign projectsoc1 = {projectsoc_ram_bus_adr, 2'd0};
assign projectsoc_axilite2wishbone1 = (projectsoc_vexiiriscv_endpoint3_payload_addr - 1'd0);
assign projectsoc_axilite2wishbone2 = (projectsoc_vexiiriscv_endpoint0_payload_addr - 1'd0);
always @(*) begin
    fsm1 = 3'd0;
    projectsoc_adapted_interface_adr = 30'd0;
    projectsoc_adapted_interface_cyc = 1'd0;
    projectsoc_adapted_interface_dat_w = 32'd0;
    projectsoc_adapted_interface_sel = 4'd0;
    projectsoc_adapted_interface_stb = 1'd0;
    projectsoc_adapted_interface_we = 1'd0;
    projectsoc_axilite2wishbone0_lowernext0 = 32'd0;
    projectsoc_axilite2wishbone0_lowernext1 = 1'd0;
    projectsoc_axilite2wishbone3_lowernext_lowernext0 = 1'd0;
    projectsoc_axilite2wishbone3_lowernext_lowernext1 = 1'd0;
    projectsoc_vexiiriscv_endpoint0_ready = 1'd0;
    projectsoc_vexiiriscv_endpoint1_ready = 1'd0;
    projectsoc_vexiiriscv_endpoint2_payload_resp = 2'd0;
    projectsoc_vexiiriscv_endpoint2_valid = 1'd0;
    projectsoc_vexiiriscv_endpoint3_ready = 1'd0;
    projectsoc_vexiiriscv_endpoint4_payload_data = 32'd0;
    projectsoc_vexiiriscv_endpoint4_payload_resp = 2'd0;
    projectsoc_vexiiriscv_endpoint4_valid = 1'd0;
    fsm1 = fsm0;
    case (fsm0)
        1'd1: begin
            projectsoc_adapted_interface_stb = 1'd1;
            projectsoc_adapted_interface_cyc = 1'd1;
            projectsoc_adapted_interface_adr = projectsoc_axilite2wishbone1[31:2];
            projectsoc_adapted_interface_sel = 4'd15;
            if (projectsoc_adapted_interface_ack) begin
                projectsoc_vexiiriscv_endpoint3_ready = 1'd1;
                projectsoc_axilite2wishbone0_lowernext0 = projectsoc_adapted_interface_dat_r;
                projectsoc_axilite2wishbone0_lowernext1 = 1'd1;
                fsm1 = 2'd2;
            end
        end
        2'd2: begin
            projectsoc_vexiiriscv_endpoint4_valid = 1'd1;
            projectsoc_vexiiriscv_endpoint4_payload_resp = 1'd0;
            projectsoc_vexiiriscv_endpoint4_payload_data = projectsoc_axilite2wishbone0;
            if (projectsoc_vexiiriscv_endpoint4_ready) begin
                fsm1 = 1'd0;
            end
        end
        2'd3: begin
            projectsoc_adapted_interface_stb = projectsoc_vexiiriscv_endpoint1_valid;
            projectsoc_adapted_interface_cyc = projectsoc_vexiiriscv_endpoint1_valid;
            projectsoc_adapted_interface_we = 1'd1;
            projectsoc_adapted_interface_adr = projectsoc_axilite2wishbone2[31:2];
            projectsoc_adapted_interface_sel = projectsoc_vexiiriscv_endpoint1_payload_strb;
            projectsoc_adapted_interface_dat_w = projectsoc_vexiiriscv_endpoint1_payload_data;
            if (projectsoc_adapted_interface_ack) begin
                projectsoc_vexiiriscv_endpoint0_ready = 1'd1;
                projectsoc_vexiiriscv_endpoint1_ready = 1'd1;
                fsm1 = 3'd4;
            end
        end
        3'd4: begin
            projectsoc_vexiiriscv_endpoint2_valid = 1'd1;
            projectsoc_vexiiriscv_endpoint2_payload_resp = 1'd0;
            if (projectsoc_vexiiriscv_endpoint2_ready) begin
                fsm1 = 1'd0;
            end
        end
        default: begin
            if ((projectsoc_vexiiriscv_endpoint3_valid & projectsoc_vexiiriscv_endpoint0_valid)) begin
                if (projectsoc_axilite2wishbone3) begin
                    projectsoc_axilite2wishbone3_lowernext_lowernext0 = 1'd0;
                    projectsoc_axilite2wishbone3_lowernext_lowernext1 = 1'd1;
                    fsm1 = 2'd3;
                end else begin
                    projectsoc_axilite2wishbone3_lowernext_lowernext0 = 1'd1;
                    projectsoc_axilite2wishbone3_lowernext_lowernext1 = 1'd1;
                    fsm1 = 1'd1;
                end
            end else begin
                if (projectsoc_vexiiriscv_endpoint3_valid) begin
                    projectsoc_axilite2wishbone3_lowernext_lowernext0 = 1'd1;
                    projectsoc_axilite2wishbone3_lowernext_lowernext1 = 1'd1;
                    fsm1 = 1'd1;
                end else begin
                    if (projectsoc_vexiiriscv_endpoint0_valid) begin
                        projectsoc_axilite2wishbone3_lowernext_lowernext0 = 1'd0;
                        projectsoc_axilite2wishbone3_lowernext_lowernext1 = 1'd1;
                        fsm1 = 2'd3;
                    end
                end
            end
        end
    endcase
end
assign adr = basiclowerer0;
assign dat_w = basiclowerer1;
assign sel = basiclowerer2;
assign cyc = basiclowerer3;
assign stb = basiclowerer4;
assign we = basiclowerer5;
assign cti = basiclowerer6;
assign bte = basiclowerer7;
assign projectsoc_adapted_interface_dat_r = dat_r;
assign projectsoc_adapted_interface_ack = (ack & (roundrobin1 == 1'd0));
assign projectsoc_adapted_interface_err = (err & (roundrobin1 == 1'd0));
assign roundrobin0 = {projectsoc_adapted_interface_cyc};
assign roundrobin1 = 1'd0;
always @(*) begin
    decoder0 = 3'd0;
    decoder0[0] = (adr[29:4] == 1'd0);
    decoder0[1] = (adr[29:4] == 1'd1);
    decoder0[2] = (adr[29:14] == 16'hf000);
end
assign projectsoc_ram_bus_adr = adr;
assign projectsoc_ram_bus_dat_w = dat_w;
assign projectsoc_ram_bus_sel = sel;
assign projectsoc_ram_bus_stb = stb;
assign projectsoc_ram_bus_we = we;
assign projectsoc_ram_bus_cti = cti;
assign projectsoc_ram_bus_bte = bte;
assign projectsoc_writetarget_adr = adr;
assign projectsoc_writetarget_dat_w = dat_w;
assign projectsoc_writetarget_sel = sel;
assign projectsoc_writetarget_stb = stb;
assign projectsoc_writetarget_we = we;
assign projectsoc_writetarget_cti = cti;
assign projectsoc_writetarget_bte = bte;
assign interface0_adr = adr;
assign interface0_dat_w = dat_w;
assign interface0_sel = sel;
assign interface0_stb = stb;
assign interface0_we = we;
assign interface0_cti = cti;
assign interface0_bte = bte;
assign projectsoc_ram_bus_cyc = (cyc & decoder0[0]);
assign projectsoc_writetarget_cyc = (cyc & decoder0[1]);
assign interface0_cyc = (cyc & decoder0[2]);
assign err = ((projectsoc_ram_bus_err | projectsoc_writetarget_err) | interface0_err);
assign timeout_waittimer0 = ((stb & cyc) & (~ack));
always @(*) begin
    ack = 1'd0;
    dat_r = 32'd0;
    timeout = 1'd0;
    ack = ((projectsoc_ram_bus_ack | projectsoc_writetarget_ack) | interface0_ack);
    dat_r = ((({32{decoder1[0]}} & projectsoc_ram_bus_dat_r) | ({32{decoder1[1]}} & projectsoc_writetarget_dat_r)) | ({32{decoder1[2]}} & interface0_dat_r));
    if (timeout_waittimer1) begin
        dat_r = 32'hffffffff;
        ack = 1'd1;
        timeout = 1'd1;
    end
end
assign timeout_waittimer1 = (timeout_waittimer2 == 1'd0);
assign projectsoc_sram_memory0 = projectsoc_ram_bus_adr[3:0];
assign projectsoc_ram_bus_dat_r = projectsoc_sram_memory1;
assign projectsoc_writetarget = {projectsoc_writetarget_adr, 2'd0};
assign projectsoc_writetarget_dat_r = 1'd0;
assign projectsoc_writetarget_err = 1'd0;
assign sys_clk_1 = sys_clk;
assign por_clk = sys_clk;
assign sys_rst = crg;
always @(*) begin
    wishbone2csr = 1'd0;
    wishbone2csr = 1'd0;
    if ((interface0_sel != 1'd0)) begin
        wishbone2csr = 1'd0;
    end
end
always @(*) begin
    interface0_ack = 1'd0;
    interface0_dat_r = 32'd0;
    interface1_adr = 14'd0;
    interface1_dat_w = 32'd0;
    interface1_re = 1'd0;
    interface1_we = 1'd0;
    wishbone2csr_fsm1 = 1'd0;
    wishbone2csr_fsm1 = wishbone2csr_fsm0;
    case (wishbone2csr_fsm0)
        1'd1: begin
            interface0_ack = 1'd1;
            interface0_dat_r = 1'd0;
            case (wishbone2csr)
                1'd0: begin
                    interface0_dat_r = interface1_dat_r;
                end
            endcase
            wishbone2csr_fsm1 = 1'd0;
        end
        default: begin
            interface1_dat_w = basiclowerer_basiclowerer;
            if ((interface0_cyc & interface0_stb)) begin
                interface1_adr = interface0_adr;
                interface1_re = ((~interface0_we) & (interface0_sel != 1'd0));
                interface1_we = (interface0_we & (interface0_sel != 1'd0));
                wishbone2csr_fsm1 = 1'd1;
            end
        end
    endcase
end
always @(*) begin
    basiclowerer0 = 30'd0;
    case (roundrobin1)
        default: begin
            basiclowerer0 = projectsoc_adapted_interface_adr;
        end
    endcase
end
always @(*) begin
    basiclowerer1 = 32'd0;
    case (roundrobin1)
        default: begin
            basiclowerer1 = projectsoc_adapted_interface_dat_w;
        end
    endcase
end
always @(*) begin
    basiclowerer2 = 4'd0;
    case (roundrobin1)
        default: begin
            basiclowerer2 = projectsoc_adapted_interface_sel;
        end
    endcase
end
always @(*) begin
    basiclowerer3 = 1'd0;
    case (roundrobin1)
        default: begin
            basiclowerer3 = projectsoc_adapted_interface_cyc;
        end
    endcase
end
always @(*) begin
    basiclowerer4 = 1'd0;
    case (roundrobin1)
        default: begin
            basiclowerer4 = projectsoc_adapted_interface_stb;
        end
    endcase
end
always @(*) begin
    basiclowerer5 = 1'd0;
    case (roundrobin1)
        default: begin
            basiclowerer5 = projectsoc_adapted_interface_we;
        end
    endcase
end
always @(*) begin
    basiclowerer6 = 3'd0;
    case (roundrobin1)
        default: begin
            basiclowerer6 = projectsoc_adapted_interface_cti;
        end
    endcase
end
always @(*) begin
    basiclowerer7 = 2'd0;
    case (roundrobin1)
        default: begin
            basiclowerer7 = projectsoc_adapted_interface_bte;
        end
    endcase
end
always @(*) begin
    basiclowerer_basiclowerer = 32'd0;
    case (wishbone2csr)
        default: begin
            basiclowerer_basiclowerer = interface0_dat_w;
        end
    endcase
end


//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------

always @(posedge por_clk) begin
    crg <= 1'd0;
end

always @(posedge sys_clk_1) begin
    if ((((projectsoc_ram_bus_cyc & projectsoc_ram_bus_stb) & projectsoc_ram_bus_ack) & (~projectsoc0))) begin
        projectsoc0 <= 1'd1;
        $display("FETCH first_byte_address=0x%08x", projectsoc1);
    end
    fsm0 <= fsm1;
    if (projectsoc_axilite2wishbone3_lowernext_lowernext1) begin
        projectsoc_axilite2wishbone3 <= projectsoc_axilite2wishbone3_lowernext_lowernext0;
    end
    if (projectsoc_axilite2wishbone0_lowernext1) begin
        projectsoc_axilite2wishbone0 <= projectsoc_axilite2wishbone0_lowernext0;
    end
    decoder1 <= decoder0;
    if (timeout_waittimer0) begin
        if ((~timeout_waittimer1)) begin
            timeout_waittimer2 <= (timeout_waittimer2 - 1'd1);
        end
    end else begin
        timeout_waittimer2 <= 20'd1000000;
    end
    projectsoc_ram_bus_ack <= 1'd0;
    if (((projectsoc_ram_bus_cyc & projectsoc_ram_bus_stb) & ((~projectsoc_ram_bus_ack) | projectsoc_sram))) begin
        projectsoc_ram_bus_ack <= 1'd1;
    end
    projectsoc_writetarget_ack <= 1'd0;
    if (((projectsoc_writetarget_cyc & projectsoc_writetarget_stb) & (~projectsoc_writetarget_ack))) begin
        projectsoc_writetarget_ack <= 1'd1;
    end
    if ((((projectsoc_writetarget_cyc & projectsoc_writetarget_stb) & (~projectsoc_writetarget_ack)) & projectsoc_writetarget_we)) begin
        if ((((projectsoc_writetarget_adr == 5'd16) & (projectsoc_writetarget_dat_w == 7'd64)) & (projectsoc_writetarget_sel == 4'd15))) begin
            $display("PASS 01: VexiiRiscv wrote 0x40 to byte address 0x40");
        end else begin
            $display("FAIL 01: wrong write");
        end
        $finish;
    end
    wishbone2csr_fsm0 <= wishbone2csr_fsm1;
    if (sys_rst) begin
        projectsoc_axilite2wishbone0 <= 32'd0;
        projectsoc_axilite2wishbone3 <= 1'd0;
        projectsoc_ram_bus_ack <= 1'd0;
        projectsoc_writetarget_ack <= 1'd0;
        projectsoc0 <= 1'd0;
        fsm0 <= 3'd0;
        decoder1 <= 3'd0;
        timeout_waittimer2 <= 20'd1000000;
        wishbone2csr_fsm0 <= 1'd0;
    end
end


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Memory rom: 16-words x 32-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: ---- | 
reg [31:0] rom[0:15];
initial begin
	$readmemh("sim_rom.init", rom);
end
reg [31:0] rom_dat0;
always @(posedge sys_clk_1) begin
	rom_dat0 <= rom[projectsoc_sram_memory0];
end
assign projectsoc_sram_memory1 = rom_dat0;


//------------------------------------------------------------------------------
// Instance VexiiRiscvLitex_70fcb4655c102be1cd666acde65d5d70 of VexiiRiscvLitex_70fcb4655c102be1cd666acde65d5d70 Module.
//------------------------------------------------------------------------------
VexiiRiscvLitex_70fcb4655c102be1cd666acde65d5d70 VexiiRiscvLitex_70fcb4655c102be1cd666acde65d5d70(
	// Inputs.
	.litex_clk                          (sys_clk_1),
	.litex_reset                        ((sys_rst | projectsoc_vexiiriscv0)),
	.pBus_arready                       (projectsoc_vexiiriscv_endpoint3_ready),
	.pBus_awready                       (projectsoc_vexiiriscv_endpoint0_ready),
	.pBus_bresp                         (projectsoc_vexiiriscv_endpoint2_payload_resp),
	.pBus_bvalid                        (projectsoc_vexiiriscv_endpoint2_valid),
	.pBus_rdata                         (projectsoc_vexiiriscv_endpoint4_payload_data),
	.pBus_rresp                         (projectsoc_vexiiriscv_endpoint4_payload_resp),
	.pBus_rvalid                        (projectsoc_vexiiriscv_endpoint4_valid),
	.pBus_wready                        (projectsoc_vexiiriscv_endpoint1_ready),
	.peripheral_externalInterrupts_port (projectsoc_vexiiriscv1),

	// Outputs.
	.debug                              (projectsoc_vexiiriscv2),
	.pBus_araddr                        (projectsoc_vexiiriscv_endpoint3_payload_addr),
	.pBus_arprot                        (projectsoc_vexiiriscv4),
	.pBus_arvalid                       (projectsoc_vexiiriscv_endpoint3_valid),
	.pBus_awaddr                        (projectsoc_vexiiriscv_endpoint0_payload_addr),
	.pBus_awprot                        (projectsoc_vexiiriscv3),
	.pBus_awvalid                       (projectsoc_vexiiriscv_endpoint0_valid),
	.pBus_bready                        (projectsoc_vexiiriscv_endpoint2_ready),
	.pBus_rready                        (projectsoc_vexiiriscv_endpoint4_ready),
	.pBus_wdata                         (projectsoc_vexiiriscv_endpoint1_payload_data),
	.pBus_wstrb                         (projectsoc_vexiiriscv_endpoint1_payload_strb),
	.pBus_wvalid                        (projectsoc_vexiiriscv_endpoint1_valid)
);

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2026-10-05 21:36:51.
//------------------------------------------------------------------------------
